# File: .github/workflows/workflow.yml

on: [push]
permissions:
      id-token: write
      contents: read
name: AzurePowerShellLoginSample

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Login via Az module
      uses: azure/login@v1
      with:
        #creds: ${{ secrets.AZURE_CREDENTIALS }}                      
        client-id: ${{ secrets.AZURE_OIDC_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        #enable-AzPSSession: true
    - name: Azure CLI Script
      uses: azure/CLI@v1
      with:
        azclientversion: latest
        inlineScript: |
          az account show
          az group list
        
